### ISSUE TITLE
Pip package is missing the assets folder

### ISSUE THREAD

**Issue by GrayJoKing** [sclamons/surface_crns#2]
When installing via pip, the package is missing the assets folder. This means when executing a manifest with the SurfaceCRNQueueSimulator it fails in pygbutton.py at line 271. Downloading the github code and copying across the `surface_crns/assets` folder solved this.

**Comment by sclamons** [comment]
I don't get this behavior, even from a fresh install. What manifest are you using? What OS/python version? Can you give me a stack trace of the exception?

**Comment by GrayJoKing** [comment]
I am on Windows 10, Python 3.9

I ran `python SurfaceCRNQueueSimulator.py -m ..\examples\Other\majority_asynchronous.txt` in the surface_crns folder and got the output

```
pygame 2.0.1 (SDL 2.0.14, Python 3.9.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Reading information from manifest file ..\examples\Other\majority_asynchronous.txt...
 Done.
Beginning Pygame setup...
Traceback (most recent call last):
  File "C:\Users\JK\Downloads\surface_crns-master\surface_crns-master\surface_crns\SurfaceCRNQueueSimulator.py", line 749, in <module>
    main()
  File "C:\Users\JK\Downloads\surface_crns-master\surface_crns-master\surface_crns\SurfaceCRNQueueSimulator.py", line 103, in main
    simulate_surface_crn(manifest_filename)
  File "C:\Users\JK\Downloads\surface_crns-master\surface_crns-master\surface_crns\SurfaceCRNQueueSimulator.py", line 261, in simulate_surface_crn
    save_image_button.setSurfaces(camera_file, green_camera_file,
  File "C:\Users\JK\AppData\Local\Programs\Python\Python39\lib\site-packages\surface_crns\pygbutton.py", line 271, in setSurfaces
    self.origSurfaceNormal = pygame.image.load(normalSurface)
FileNotFoundError: No such file or directory.

```

**Comment by sclamons** [comment]
Updated pypi to 1.2. Try that.

**Comment by GrayJoKing** [comment]
The assets folder still seems to be missing. Doing a fresh install on a different computer, I see that the version number has updated, but running the same command as before (though with a new copy of an example manifest file) results in the exact same error.

**Comment by sclamons** [comment]
That doesn't make a ton of sense -- assets is definitely in the source files now. Can you check with that fresh install to see if the assets folder is actually there or not? There may be something else going on.

**Comment by GrayJoKing** [comment]
Using a new empty venv:

```
(myvenv) guest@guest-Aspire-V3-571G:~/Documents/myvenv$ pip install surface_crns
Collecting surface_crns
  Downloading surface_crns-1.2-py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 2.0 MB/s 
Collecting pygame
  Downloading pygame-2.0.1-cp38-cp38-manylinux1_x86_64.whl (11.8 MB)
     |████████████████████████████████| 11.8 MB 2.2 MB/s 
Collecting numpy
  Downloading numpy-1.21.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.8 MB)
     |████████████████████████████████| 15.8 MB 2.6 MB/s 
Installing collected packages: pygame, numpy, surface-crns
Successfully installed numpy-1.21.1 pygame-2.0.1 surface-crns-1.2
(myvenv) guest@guest-Aspire-V3-571G:~/Documents/myvenv$ ls -l lib/python3.8/site-packages/surface_crns
total 112
drwxrwxr-x 3 guest guest  4096 Jul 22 22:48 base
-rw-rw-r-- 1 guest guest    26 Jul 22 22:48 constants.py
-rw-rw-r-- 1 guest guest  2102 Jul 22 22:48 generate_random_colors.py
-rw-rw-r-- 1 guest guest   451 Jul 22 22:48 __init__.py
drwxrwxr-x 3 guest guest  4096 Jul 22 22:48 models
drwxrwxr-x 3 guest guest  4096 Jul 22 22:48 options
-rw-rw-r-- 1 guest guest  8827 Jul 22 22:48 ordered_dict.py
drwxrwxr-x 3 guest guest  4096 Jul 22 22:48 profiling
drwxrwxr-x 2 guest guest  4096 Jul 22 22:48 __pycache__
-rw-rw-r-- 1 guest guest 14612 Jul 22 22:48 pygbutton.py
-rw-rw-r-- 1 guest guest  6368 Jul 22 22:48 random_color.py
drwxrwxr-x 3 guest guest  4096 Jul 22 22:48 readers
drwxrwxr-x 3 guest guest  4096 Jul 22 22:48 simulators
-rw-rw-r-- 1 guest guest 32303 Jul 22 22:48 SurfaceCRNQueueSimulator.py
drwxrwxr-x 3 guest guest  4096 Jul 22 22:48 views
```

There's no assets folder present.

**Comment by sclamons** [comment]
I think I figured it out -- setup.py wasn't configured to include data files, so none of the wheels included assets. I guess all of the systems I tested on used the raw tar instead of a wheel. In any case, try again with version 1.2.1 and let me know if it works or not.

**Comment by sclamons** [comment]
@GrayJoKing Did this work?

**Comment by GrayJoKing** [comment]
Sorry about not replying, this slipped my mind. Yes, the pip installation now includes the assets folder! It all works well now.
